### ISSUE TITLE
function with parameters

### ISSUE THREAD

**Issue by surendranath-orderpoint** [RIAEvangelist/js-queue#5]
Is there any way to pass parameters to makeRequest function ?

**Comment by RIAEvangelist** [comment]
I don't understand your question. Could you explain what you want to do with more detail?

Thanks!

**Comment by surendranath-orderpoint** [comment]
How can i pass data to function we are adding in queue ? In the below example is there a way to pass i value inside for loop to makeRequest function ?

```javascript
var Queue=require('js-queue');
    //create a new queue instance
    var queue=new Queue;

    for(var i=0; i<50; i++){
        //add a bunch of stuff to the queue
        queue.add(makeRequest);
    }

    function makeRequest(){
        //do stuff
        console.log('making some request');

        this.next();
    }
```

Thanks

**Comment by RIAEvangelist** [comment]
``` js

const Queue=require('js-queue');
//create a new queue instance
var queue=new Queue;

for(var i=0; i<50; i++){
    //add a bunch of stuff to the queue
    queue.add(
        makeRequest.bind(this,i)
    );
}

function makeRequest(whatIsI){
    //do stuff
    console.log(`making some request i=${whatIsI}`);

    this.next();
}
    
```

I hope this helps, I did not actually test the code though, so you may need to tweak it. If this does help, please remember to close this issue so I know you are ok.

Good luck.

**Comment by surendranath-orderpoint** [comment]
@RIAEvangelist  thanks for your prompt reply, unfortunately it is not working, getting below error.

```javascript
TypeError: this.next is not a function
```

Thanks!

**Comment by RIAEvangelist** [comment]
Oh, I see what my mistake was. In the `.bind` call, change `this` to the reference to your `queue` instance.

**Comment by surendranath-orderpoint** [comment]
It is working now, Thanks.
